import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.nav}>
          <div className={styles["nav-links"]}>
            <Link href="/informacion" className={styles["nav-link"]}>Sacar turno</Link>
            <Link href="/ProximoTurno" className={styles["nav-link"]}>Próximo turno</Link>
            <Link href="/Perfil" className={styles["nav-link"]}>Perfil</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
