import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";
import { Providers } from "./providers";
import Perfil from "./Perfil/page";
import { ProtectedRoutes } from "./components/Utils/ProtectedRoutes";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <Providers>
            <ProtectedRoutes>
              <Header />
            {children}
          
            </ProtectedRoutes>
          </Providers>
      </body>
    </html>
  );
}
